[package]
name = "interop-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.22.1"
clap = "4.5.4"
miette = { version = "7.2.0", features = ["fancy"] }
rsasl = { path = "../..", default-features = false, features = ["provider_base64"] }
