[package]
name = "interop-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsasl = { path = "../..", features = ["provider_base64", "gssapi"] }
rustls = "0.20"
url = "2"

clap = "3.2.23"

miette = { version = "4.7", features = ["fancy"] }
# Required for -Zminimal-versions
is_ci = "1.1.1"
# Required for -Zminimal-versions
regex = "1.10.2"

hex = "0.4"
