[package]
name = "interop-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "4.5.4"
hex = "0.4.3"
# Required for -Zminimal-versions
is_ci = "1.2.0"
miette = { version = "7.2.0", features = ["fancy"] }
# Required for -Zminimal-versions
regex = "1.10.4"
rsasl = { path = "../..", default-features = false, features = ["provider_base64", "gssapi"] }
rustls = { version = "0.23.7", default-features = false, features = ["std", "tls12", "logging", "ring"] }
url = "2.5.0"
